### ISSUE TITLE
How to change the Title screen texts and the texts leading up to the movie?

### ISSUE THREAD

**Issue by akefa12** [adafruit/pi_video_looper#113]
Thank you for opening an issue on an Adafruit Python library repository.  To
improve the speed of resolution please review the following guidelines and
common troubleshooting steps below before creating the issue:

- **Do not use GitHub issues for troubleshooting projects and issues.**  Instead use
  the forums at http://forums.adafruit.com to ask questions and troubleshoot why
  something isn't working as expected.  In many cases the problem is a common issue
  that you will more quickly receive help from the forum community.  GitHub issues
  are meant for known defects in the code.  If you don't know if there is a defect
  in the code then start with troubleshooting on the forum first.

- **If following a tutorial or guide be sure you didn't miss a step.** Carefully
  check all of the steps and commands to run have been followed.  Consult the
  forum if you're unsure or have questions about steps in a guide/tutorial.

- **For Python/Raspberry Pi projects check these very common issues to ensure they don't apply**:

  - If you are receiving an **ImportError: No module named...** error then a
    library the code depends on is not installed.  Check the tutorial/guide or
    README to ensure you have installed the necessary libraries.  Usually the
    missing library can be installed with the `pip` tool, but check the tutorial/guide
    for the exact command.  

  - **Be sure you are supplying adequate power to the board.**  Check the specs of
    your board and power in an external power supply.  In many cases just
    plugging a board into your computer is not enough to power it and other
    peripherals.

  - **Double check all soldering joints and connections.**  Flakey connections
    cause many mysterious problems.  See the [guide to excellent soldering](https://learn.adafruit.com/adafruit-guide-excellent-soldering/tools) for examples of good solder joints.

If you're sure this issue is a defect in the code and checked the steps above
please fill in the following fields to provide enough troubleshooting information.
You may delete the guideline and text above to just leave the following details:

- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.):  **INSERT PLATFORM/OPERATING
  SYSTEM HERE**

- Python version (run `python -version` or `python3 -version`):  **INSERT PYTHON
  VERSION HERE**

- Error message you are receiving, including any Python exception traces:  **INSERT
  ERROR MESAGE/EXCEPTION TRACES HERE***

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): **LIST REPRO STEPS BELOW**

**Comment by tofuSCHNITZEL** [comment]
Hi,
there is not really a title screen per se... only a gui thats more for educational purposes (the countdown - number of movies etc) so if you maybe go into more detail what you want to achieve, we will find a solution.
cheers

**Comment by universalsolution** [comment]
Dear tofuSCHNITZEL,
I have a more/less similiar question. I hope it's fine to respond here instead of opening a new topic.
I installed the video_looper with the install.sh file on DietPi (image by videolooper.de). All running and good.
Now I tried to change a little bit of the code, basically for learning and better understanding... , like erasing the "number of movies" message, just leaving the counter.

I tried to deactivate lines 246ff in the pi_video_looper/Adafruit_Video_Looper/video_looper.py file, but without success. 
It seems like there is somewhere a "compiled" version of the phyton program somewhere in the system, maybe the install.sh file is putting the video_looper file somewhere else? I just found a .egg file somewhere in /var/lib ... but I guess this has nothing do to with it. 

So my simple question: How can I play around and edit elements in the code of the various .py files in pi_video_looper/Adafruit_Video_Looper/

Thanks very much! And if this is the wrong place to ask, please excuse, I'm also new at github...

**Comment by tofuSCHNITZEL** [comment]
Hi!
since the videolooper runs as a module you have to run `python3 setup.py install --force` after changes to the sourcecode so it gets compiled into the module code.

cheers

**Comment by sionglow** [comment]
Would you consider putting the messages such as "Insert USB drive etc." and the subsequent message and count down as part of the video_looper.ini? Thank you for sharing all of your work!

**Comment by tofuSCHNITZEL** [comment]
Hi @sionglow,
could you explain your usecase?
the messages are more for an educational purpose... I guess in a "real" setup you would not want to display anything besides the videos.. and chaning the text is fairly easy directly in the source code (since you can just look for the words you want to change)

cheers

**Comment by sionglow** [comment]
> 
> 
> Hi!
> since the videolooper runs as a module you have to run `python3 setup.py install --force` after changes to the sourcecode so it gets compiled into the module code.
> 
> cheers

Thank you! That worked - found the lines to change and recompiled as you suggested and was easily able to change the idle text. Please do close the this issue.
