### ISSUE TITLE
OMXplayer sound issue with -both option

### ISSUE THREAD

**Issue by adrianriffo** [adafruit/pi_video_looper#114]
Dear pi_video_looper team, 

I love this script, I have been using it in many art center where I work as exhibition technician/ technical manager.
I can not imagine to keep up working without this wonderful media player. Thank you for developping this!

I am so sad to have lost the option of playing the audio through HDMI and mini-jack on RPi4. It is one or the other. Which makes it less handy when working on an exhibition set up.

Is there a workaround with OMXplayer to get both ouputs without having the mini-jack output distorted?
As its github page says OMXplayer is deprecated for using non RPi4 compatible modules and that efforts are joint on vlc, do you think a version based on vlc is possible to imagine?

Looking forward to hearing from you.

Cheers, 

RPi 4, 2Go

**Comment by christiansievers** [comment]
Re analogue sound: Have you tried a Hifi DAC? Worth trying if you can get both outputs?

I'm sorry to hear about omxplayer being deprecated, and all these changes required because the rpi4 is so different. I worry we're losing exactly what you describe, a super-simple, no frills media player. (I guess people could just continue to use the rpi3, but they would have to buy it just for one exhibition, whereas earlier a Raspberry is just what you'd have around anyway.)
