### ISSUE TITLE
Single loop, skip to next video

### ISSUE THREAD

**Issue by juri74** [adafruit/pi_video_looper#117]
Dear pi_video_looper team,
Thank you so much for this software you'll never imagine how this is useful to me!
this is not an issue but some sort of enhancement/feature request.

the normal behaviour of video looper is this: find all video files, play all files one by one and then restart from the first.
i use my raspberry pi zero w as a background video generator, it would be very useful to me to have a bunch of video in the sd/usb but with a different behaviour:
play and loop one single file until a skip command is issued, at this point video looper should start next video and play it endless until skip is issued.
a really nice feature should be a button connected to the gpio pins to skip video (not pin 5+6 that i already use for shutdown the raspberry pi)
thank you so much!

**Comment by tofuSCHNITZEL** [comment]
Hi,
since this sounds like a very special case to me, you could take a shot and try to program it yourself. 
there is already the feature to read iterations from the filename... could be adapted for inf looping and then you would need to adapt the skip function to not go to the next iteration but video - and add some python gpio code to have the skip activate with the GPIO pins.
cheers
