### ISSUE TITLE
Pause vs stop

### ISSUE THREAD

**Issue by Chrisgraue** [adafruit/pi_video_looper#163]
Pause (S key) doesn't work as expected.

Pressing S stops video playback, turning screen black. When S is pressed again, the next video in the playlist starts from the beginning.

Is it possible to have the same video file resume from the moment it was paused? Like how a pause/play button normally works on most devices?

**Comment by tofuSCHNITZEL** [comment]
Hi,
the documentation states that S is stop/start and not pause. Unfortunately the way the video looper is currently designed, there is no way to send "signals" to the software (omxplayer) that actually plays the videos to make them halt or resume.
But I can have a look to change the behaviour so that pressing S again starts the same video from the beginning where S was pressed the first time...

Thanks for understanding.
Cheers

**Comment by Redacted99** [comment]
Sending a command to omxplayer is pretty easy.  I have coded it for my application and can add it to the software if you approve.  Basically add stdin=subprocess.PIPE, to the popen and then add a pause function to omxplayer.py that sends a space character to omxplayer when you want to pause it.  A few lines of code in omxplayer.py and then keystroke glue in video_looper

**Comment by tofuSCHNITZEL** [comment]
Great, please open a pull request!

**Comment by cinghialino** [comment]
Oh I would love this too! I made a compilation of video for my aging father, so the ability to pause a movie and then resume it at a later time would be amazing.

**Comment by tofuSCHNITZEL** [comment]
it will come in version 1.0.13 which is currently in the "next" branch and needs to be tested before it is "released"

**Comment by tofuSCHNITZEL** [comment]
pause is implemented in https://github.com/adafruit/pi_video_looper/releases/tag/v1.0.13
