### ISSUE TITLE
location of video_looper.ini

### ISSUE THREAD

**Issue by fredericofs** [adafruit/pi_video_looper#7]
How do I change the location of video.looper.ini from /boot to other dir?

I tried creating a symlink but it seems boot partition is vfat, and vfat dont support symlinks..

**Comment by tdicola** [comment]
Oh your best bet for changing the config location is to slightly modify the code.  Change this line so that it points at a different spot instead of /boot/video_looper.ini: https://github.com/adafruit/pi_video_looper/blob/master/Adafruit_Video_Looper/video_looper.py#L242  Then reinstall the looper code by running in a terminal inside the root folder for this project:
```
sudo python setup.py install --force
```
The --force option should make sure your modified version is installed and overwrites the old version.  Give that a shot and let me know if you see issues, thanks!
